version: "3.9"
services:
  hemlock:
    build:
      args:
        - LATEST=branchtaken/hemlock:base
        - USER=hemlock
      context: ${HOME}
      dockerfile: .dotfiles/Dockerfile
      target: latest
    cap_add:
      - ALL
    command: /usr/bin/tmux
    environment:
      - SSH_AUTH_SOCK
    container_name: cevans87__hemlock
    extends:
      file: ./Hemlock/docker-compose.yml
      service: base
    image: cevans87/hemlock
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./Hemlock:/home/hemlock/Hemlock
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
  modulo:
    build:
      args:
        - USER=modulo
      context: ${HOME}
      dockerfile: .dotfiles/Dockerfile
      target: latest
    cap_add:
      - ALL
    #command: /usr/bin/tmux
    command: /bin/bash
    container_name: cevans87__modulo
    environment:
      - SSH_AUTH_SOCK
    image: cevans87/modulo
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./.dotfiles:/home/modulo/.dotfiles
      - /var/run/docker.sock:/var/run/docker.sock
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
