version: "3.9"
services:
  cse503:
    build:
      args:
        - PLATFORM=linux/amd64
        - USER=cse503
      context: /home/modulo
      dockerfile: .dotfiles/07.symlink/2.home/modulo/Dockerfile
      target: latest
    command: /usr/bin/tmux
    environment:
      - SSH_AUTH_SOCK
    container_name: modulo__cse503
    extends:
      file: ./cse507/docker-compose.yml
      service: base
    image: modulo/cse503
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /home/modulo/.bash_history:/home/cse503/.bash_history
      - /home/modulo/.ssh:/home/cse507/.ssh
      - /home/modulo/IdeaProjects/AgileBoot-Back-End:/home/cse503/AgileBoot-Back-End
      - /home/modulo/IdeaProjects/avaje-inject:/home/cse503/avaje-inject
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
  cse507:
    build:
      args:
        - LATEST=cevans87/cse507:base
        - PLATFORM=linux/amd64
        - USER=cse507
      context: /home/modulo
      dockerfile: .dotfiles/07.symlink/2.home/modulo/Dockerfile
      target: latest
    command: /usr/bin/tmux
    environment:
      - SSH_AUTH_SOCK
    container_name: modulo__cse507
    extends:
      file: ./cse507/docker-compose.yml
      service: base
    image: modulo/cse507
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /home/modulo/.bash_history:/home/cse507/.bash_history
      - /home/modulo/.ssh:/home/cse507/.ssh
      - /home/modulo/cse507:/home/cse507/cse507
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
  fuel-core:
    build:
      args:
        - PLATFORM
        - LATEST=FuelLabs/fuel-core
        - USER=fuel-core
      context: /home/modulo
      dockerfile: .dotfiles/07.symlink/2.home/modulo/Dockerfile
      target: latest
    cap_add:
      - ALL
    command: /usr/bin/tmux
    environment:
      - SSH_AUTH_SOCK
    container_name: modulo__fuel_core
    extends:
      file: ./Hemlock/docker-compose.yml
      service: base
    image: modulo/fuel-core
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /home/modulo/.bash_history:/home/hemlock/.bash_history
      - /home/modulo/.ssh:/home/hemlock/.ssh
      - /home/modulo/Hemlock:/home/hemlock/Hemlock
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
  hemlock:
    build:
      args:
        - PLATFORM
        - LATEST=branchtaken/hemlock:base
        - USER=hemlock
      context: /home/modulo
      dockerfile: .dotfiles/07.symlink/2.home/modulo/Dockerfile
      target: latest
    cap_add:
      - ALL
    command: /usr/bin/tmux
    environment:
      - SSH_AUTH_SOCK
    container_name: modulo__hemlock
    extends:
      file: ./Hemlock/docker-compose.yml
      service: base
    image: modulo/hemlock
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /home/modulo/.bash_history:/home/hemlock/.bash_history
      - /home/modulo/.ssh:/home/hemlock/.ssh
      - /home/modulo/Hemlock:/home/hemlock/Hemlock
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
  modulo:
    build:
      args:
        - PLATFORM
        - USER=modulo
      context: /home/modulo
      dockerfile: .dotfiles/07.symlink/2.home/modulo/Dockerfile
      target: latest
      ssh:
        - default
    cap_add:
      - ALL
    command: /usr/bin/tmux
    container_name: modulo__modulo
    environment:
      - SSH_AUTH_SOCK
    image: modulo/modulo
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /home/modulo/.bash_history:/home/modulo/.bash_history
      - /home/modulo/.ssh:/home/modulo/.ssh
      - /home/modulo/Hemlock:/home/modulo/Hemlock
      - /var/run/docker.sock:/var/run/docker.sock
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
