version: "3.9"
services:
  hemlock:
    build:
      args:
        - PLATFORM
        - LATEST=branchtaken/hemlock:base
        - USER=hemlock
      context: /home/modulo/.dotfiles
      dockerfile: 09.dockerfile/modulo/hemlock
      target: latest
    cap_add:
      - ALL
    command: /usr/bin/tmux
    environment:
      - SSH_AUTH_SOCK
    container_name: modulo__hemlock
    extends:
      file: ./Hemlock/docker-compose.yml
      service: base
    image: modulo/hemlock
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /home/modulo/.bash_history:/home/hemlock/.bash_history
      - /home/modulo/.ssh:/home/hemlock/.ssh
      - /home/modulo/Hemlock:/home/hemlock/Hemlock
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
  modulo:
    build:
      args:
        - PLATFORM
        - USER=modulo
      context: /home/modulo/.dotfiles
      dockerfile: 09.dockerfile/modulo/modulo
      target: latest
      ssh:
        - default
    cap_add:
      - ALL
    command: /usr/bin/tmux
    container_name: modulo__modulo
    environment:
      - SSH_AUTH_SOCK
    image: modulo/modulo
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /home/modulo/.bash_history:/home/modulo/.bash_history
      - /home/modulo/.ssh:/home/modulo/.ssh
      - /home/modulo/Hemlock:/home/modulo/Hemlock
      - /var/run/docker.sock:/var/run/docker.sock
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
