version: "3.9"
services:
  hemlock:
    build:
      args:
        - LATEST=branchtaken/hemlock:base
        - USER=hemlock
      context: /home/cevans
      dockerfile: .dotfiles/07.symlink/2.home/default/Dockerfile
      target: latest
    cap_add:
      - ALL
    command: /usr/bin/tmux
    environment:
      - SSH_AUTH_SOCK
    container_name: cevans87__hemlock
    extends:
      file: ./Hemlock/docker-compose.yml
      service: base
    image: cevans87/hemlock
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /home/cevans:/home/cevans
      - /home/cevans/.bash_history:/home/hemlock/.bash_history
      - /home/cevans/.dotfiles:/home/hemlock/.dotfiles
      - /home/cevans/.ssh:/home/hemlock/.ssh
      - /home/cevans/Hemlock:/home/hemlock/Hemlock
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
  mod:
    build:
      args:
        - USER=mod
      context: /home/cevans
      dockerfile: .dotfiles/07.symlink/2.home/default/Dockerfile
      target: latest
    cap_add:
      - ALL
    command: /usr/bin/tmux
    container_name: cevans87__modulo
    environment:
      - SSH_AUTH_SOCK
    image: cevans87/modulo
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - /home/cevans:/home/cevans
      - /home/cevans/.bash_history:/home/modulo/.bash_history
      - /home/cevans/.dotfiles:/home/modulo/.dotfiles
      - /home/cevans/.ssh:/home/modulo/.ssh
      - /home/cevans/Hemlock:/home/modulo/Hemlock
      - /var/run/docker.sock:/var/run/docker.sock
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
